# Aider configuration for local development with Ollama
# Place this file at the root of your git repository

##########################################################
# Model Configuration
##########################################################

# Primary model - Qwen2.5-Coder 14B is excellent for M3 Pro with 18GB RAM
model: ollama_chat/qwen2.5-coder:14b

# Model aliases for easy switching
alias:
  - "main:ollama_chat/qwen2.5-coder:14b"
  - "fast:ollama_chat/qwen2.5-coder:7b"
  - "large:ollama_chat/qwen2.5-coder:32b"

##########################################################
# Ollama Environment Configuration
##########################################################

set-env:
  - OLLAMA_API_BASE=http://127.0.0.1:11434
  - OLLAMA_CONTEXT_LENGTH=32768  # Good context window for 14B model

##########################################################
# Files to Always Include
##########################################################

# Read-only files that provide project context
read:
  - CONVENTIONS.md        # Project coding standards and conventions
  - README.md             # Project overview and setup instructions
  - pyproject.toml        # Dependencies and project metadata
  - CONTRIBUTING.md       # Contribution guidelines (if present)

##########################################################
# Git and Repository Settings
##########################################################

# Enable auto-commits for changes
auto-commits: true

# Add .aider* files to .gitignore automatically
gitignore: true

# Enable repo mapping for better context (adjust tokens as needed)
map-tokens: 2048
map-refresh: auto

##########################################################
# Common Ignore Patterns
##########################################################

# Specify the aider ignore file
aiderignore: .aiderignore

##########################################################
# Development Settings
##########################################################

# Show diffs when committing
show-diffs: true

# Enable file watching for better integration
watch-files: true

# Suggest shell commands when appropriate
suggest-shell-commands: true

# Use multiline input mode
multiline: false

# Enable notifications when responses are ready
notifications: false

##########################################################
# Output and Display Settings
##########################################################

# Use colors suitable for terminal
pretty: true
stream: true

# Code highlighting theme (options: default, monokai, solarized-dark, etc.)
code-theme: monokai

##########################################################
# Editor Configuration
##########################################################

# Set preferred editor for /editor command
# editor: code --wait  # Uncomment and adjust for your preferred editor